error handle for no translations

diff --git a/.github/workflows/diff-translations.yml b/.github/workflows/diff-translations.yml
--- a/.github/workflows/diff-translations.yml
+++ b/.github/workflows/diff-translations.yml
@@ -51,7 +51,15 @@ jobs:
           | tee -a $GITHUB_OUTPUT
 
     - name: get this versions translations
-      run: .github/scripts/scrape-translations.sh > current-translations.csv
+      run: |
+        translations=$(.github/scripts/scrape-translations.sh)
+        exit_code=$?
+        if [ $exit_code -eq 0 ]; then
+         echo "$translations" > current-translations.csv
+        else
+          echo "Script failed with exit code $exit_code."
+        fi
+
     - name: Upload translations
       id: translations-upload
       uses: actions/upload-artifact@v4
@@ -71,7 +79,7 @@ jobs:
       env:
         cversion: ${{ steps.currentv.outputs.current_version }}
       run: |
-        aws s3 --no-progress cp translations.csv s3://bes-tamanu-translations/$cversion.csv
+        aws s3 --no-progress cp current-translations.csv s3://bes-tamanu-translations/$cversion.csv
 
     - name: Download previous versions translations from s3
       env:
